# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  epharmacyrestapi:
    image: epharmacyrestapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    restart: unless-stopped
    ports:
      - 5000:5000

networks:
  default:
    external:
      name: poneauatcallcenter_api-network
