FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:80 
EXPOSE 80

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["src/EPharmacy.RESTApi/EPharmacy.RestAPI.csproj", "src/EPharmacy.RESTApi/"]
COPY ["src/EPharmacy.Application/EPharmacy.Application.csproj", "src/EPharmacy.Application/"]
COPY ["src/EPharmacy.Domain/EPharmacy.Domain.csproj", "src/EPharmacy.Domain/"]
COPY ["src/EPharmacy.Infrastructure/EPharmacy.Infrastructure.csproj", "src/EPharmacy.Infrastructure/"]

RUN dotnet restore "src/EPharmacy.RESTApi/EPharmacy.RestAPI.csproj"
COPY . .
WORKDIR "/src/src/EPharmacy.RESTApi"
RUN dotnet build "EPharmacy.RestAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EPharmacy.RestAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EPharmacy.RESTApi.dll"]
